<h1>Peer-graded Assignment: Segmenting and Clustering Neighborhoods in Toronto</h1>

In [1]:
# library to handle data in a vectorized manner
import numpy as np 
# library for data analsysis
import pandas as pd

In [2]:
import requests
from pandas import DataFrame
from tabulate import tabulate
from bs4 import BeautifulSoup

df=pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M')[0]
df.head()

  Postal Code           Borough              Neighbourhood
0         M1A      Not assigned               Not assigned
1         M2A      Not assigned               Not assigned
2         M3A        North York                  Parkwoods
3         M4A        North York           Victoria Village
4         M5A  Downtown Toronto  Regent Park, Harbourfront

In [3]:
#Renaming columns

df.columns = ['Postcode','Borough','Neighbourhood']
df.head()

  Postcode           Borough              Neighbourhood
0      M1A      Not assigned               Not assigned
1      M2A      Not assigned               Not assigned
2      M3A        North York                  Parkwoods
3      M4A        North York           Victoria Village
4      M5A  Downtown Toronto  Regent Park, Harbourfront

In [4]:
#Delete the first row with index 0

df1 = df.drop(df.index[0])
df1.head()

  Postcode           Borough                     Neighbourhood
1      M2A      Not assigned                      Not assigned
2      M3A        North York                         Parkwoods
3      M4A        North York                  Victoria Village
4      M5A  Downtown Toronto         Regent Park, Harbourfront
5      M6A        North York  Lawrence Manor, Lawrence Heights

In [5]:
#Deleting rows that doesn't have an assignd Borough
df2 = df1[df1.Borough != 'Not assigned']
df2.head()

  Postcode           Borough                                Neighbourhood
2      M3A        North York                                    Parkwoods
3      M4A        North York                             Victoria Village
4      M5A  Downtown Toronto                    Regent Park, Harbourfront
5      M6A        North York             Lawrence Manor, Lawrence Heights
6      M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government

In [6]:
#If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.
pd.options.mode.chained_assignment = None

df2.Neighbourhood[df2.Neighbourhood == "Not assigned"] = df2.Borough

df2.head(10)

   Postcode           Borough                                Neighbourhood
2       M3A        North York                                    Parkwoods
3       M4A        North York                             Victoria Village
4       M5A  Downtown Toronto                    Regent Park, Harbourfront
5       M6A        North York             Lawrence Manor, Lawrence Heights
6       M7A  Downtown Toronto  Queen's Park, Ontario Provincial Government
8       M9A         Etobicoke      Islington Avenue, Humber Valley Village
9       M1B       Scarborough                               Malvern, Rouge
11      M3B        North York                                    Don Mills
12      M4B         East York              Parkview Hill, Woodbine Gardens
13      M5B  Downtown Toronto                     Garden District, Ryerson

In [7]:
# Combining Neighbourhoods with the same Boroughs

df3 = df2.groupby(['Postcode','Borough'])['Neighbourhood'].agg(lambda x: tuple(x)).reset_index()
df3.head()

  Postcode      Borough                              Neighbourhood
0      M1B  Scarborough                          (Malvern, Rouge,)
1      M1C  Scarborough  (Rouge Hill, Port Union, Highland Creek,)
2      M1E  Scarborough       (Guildwood, Morningside, West Hill,)
3      M1G  Scarborough                                  (Woburn,)
4      M1H  Scarborough                               (Cedarbrae,)

In [15]:
# Combining Neighbourhoods with the same Boroughs

df3 = df2.groupby(['Postcode','Borough'])['Neighbourhood'].agg(lambda x: tuple(x)).reset_index()
df3.head(60)

,Postcode,Borough,Neighbourhood
0,M1B,Scarborough,"(Malvern, Rouge,)"
1,M1C,Scarborough,"(Rouge Hill, Port Union, Highland Creek,)"
2,M1E,Scarborough,"(Guildwood, Morningside, West Hill,)"
3,M1G,Scarborough,"(Woburn,)"
4,M1H,Scarborough,"(Cedarbrae,)"
5,M1J,Scarborough,"(Scarborough Village,)"
6,M1K,Scarborough,"(Kennedy Park, Ionview, East Birchmount Park,)"
7,M1L,Scarborough,"(Golden Mile, Clairlea, Oakridge,)"
8,M1M,Scarborough,"(Cliffside, Cliffcrest, Scarborough Village We..."
9,M1N,Scarborough,"(Birch Cliff, Cliffside West,)"
10,M1P,Scarborough,"(Dorset Park, Wexford Heights, Scarborough Tow..."
11,M1R,Scarborough,"(Wexford, Maryvale,)"
12,M1S,Scarborough,"(Agincourt,)"
13,M1T,Scarborough,"(Clarks Corners, Tam O'Shanter, Sullivan,)"
14,M1V,Scarborough,"(Milliken, Agincourt North, Steeles East, L'Am..."
15,M1W,Scarborough,"(Steeles West, L'Amoreaux West,)"
16,M1X,Scarborough,"(Upper Rouge,)"
17,M2H,North York,"(Hillcrest Village,)"
18,M2J,North York,"(Fairview, Henry Farm, Oriole,)"
19,M2K,North York,"(Bayview Village,)"
20,M2L,North York,"(York Mills, Silver Hills,)"
21,M2M,North York,"(Willowdale, Newtonbrook,)"
22,M2N,North York,"(Willowdale, Willowdale East,)"
23,M2P,North York,"(York Mills West,)"
24,M2R,North York,"(Willowdale, Willowdale West,)"
25,M3A,North York,"(Parkwoods,)"
26,M3B,North York,"(Don Mills,)"
27,M3C,North York,"(Don Mills,)"
28,M3H,North York,"(Bathurst Manor, Wilson Heights, Downsview Nor..."
29,M3J,North York,"(Northwood Park, York University,)"
30,M3K,North York,"(Downsview,)"
31,M3L,North York,"(Downsview,)"
32,M3M,North York,"(Downsview,)"
33,M3N,North York,"(Downsview,)"
34,M4A,North York,"(Victoria Village,)"
35,M4B,East York,"(Parkview Hill, Woodbine Gardens,)"
36,M4C,East York,"(Woodbine Heights,)"
37,M4E,East Toronto,"(The Beaches,)"
38,M4G,East York,"(Leaside,)"
39,M4H,East York,"(Thorncliffe Park,)"
40,M4J,East York,"(East Toronto, Broadview North (Old East York),)"
41,M4K,East Toronto,"(The Danforth West, Riverdale,)"
42,M4L,East Toronto,"(India Bazaar, The Beaches West,)"
43,M4M,East Toronto,"(Studio District,)"
44,M4N,Central Toronto,"(Lawrence Park,)"
45,M4P,Central Toronto,"(Davisville North,)"
46,M4R,Central Toronto,"(North Toronto West, Lawrence Park,)"
47,M4S,Central Toronto,"(Davisville,)"
48,M4T,Central Toronto,"(Moore Park, Summerhill East,)"
49,M4V,Central Toronto,"(Summerhill West, Rathnelly, South Hill, Fores..."
50,M4W,Downtown Toronto,"(Rosedale,)"
51,M4X,Downtown Toronto,"(St. James Town, Cabbagetown,)"
52,M4Y,Downtown Toronto,"(Church and Wellesley,)"
53,M5A,Downtown Toronto,"(Regent Park, Harbourfront,)"
54,M5B,Downtown Toronto,"(Garden District, Ryerson,)"
55,M5C,Downtown Toronto,"(St. James Town,)"
56,M5E,Downtown Toronto,"(Berczy Park,)"
57,M5G,Downtown Toronto,"(Central Bay Street,)"
58,M5H,Downtown Toronto,"(Richmond, Adelaide, King,)"
59,M5J,Downtown Toronto,"(Harbourfront East, Union Station, Toronto Isl..."